/* ---------------------------------------------------------------------------
   Carta digital de La Dulce — Los Abrigos, Tenerife.
   Comida: transcrita de la carta física oficial (precios y descripciones
   actualizados). Bebidas y postres: pendientes de verificar contra la carta
   física de bebidas — los precios provienen de la web anterior.
   --------------------------------------------------------------------------- */

export type Dish = { name: string; price: string; note?: string };
export type Category = {
  id: string;
  title: string;
  note?: string;
  dishes: Dish[];
};

// IDs de las categorías de bebidas — el resto se considera comida. Se usa para
// separar la carta en dos menús (Comida / Bebidas) en CartaView.
export const DRINK_IDS = [
  "zumos",
  "batidos",
  "refrescos",
  "cafe",
  "cerveza",
  "vino",
  "sidra",
  "cocteles",
  "vodka",
  "licores",
  "vermut",
  "gin",
  "ron",
  "tequila",
  "brandy",
  "chupitos",
  "whisky",
] as const;

// Foto de cabecera por categoría (independiente del idioma). Clave = Category.id.
export const CATEGORY_IMAGES: Record<string, string> = {
  brunch: "/photos/brunch.jpg",
  desayunos: "/photos/breakfast.jpg",
  pancakes: "/photos/pancake-pistacho.jpg",
  tostas: "/photos/toasts.jpg",
  croissants: "/menu/croissants.jpg",
  bagels: "/menu/bagels.jpg",
  bocadillos: "/photos/bocadillos.jpg",
  pulgas: "/photos/pulgas.jpg",
  sandwiches: "/photos/sandwiches.jpg",
  bowls: "/menu/bowls.jpg",
  burgers: "/photos/burger.jpg",
  ensaladas: "/photos/salads.jpg",
  platos: "/menu/platos.jpg",
  picoteo: "/photos/sharing.jpg",
  postres: "/menu/postres.jpg",
  zumos: "/photos/drink-pink.jpg",
  batidos: "/photos/drink-green.jpg",
  cafe: "/photos/coffee.jpg",
  refrescos: "/photos/softdrinks.jpg",
  cerveza: "/photos/beer.jpg",
  cocteles: "/photos/cocktail.jpg",
};

// object-position overrides so tall/portrait photos crop to the food (not the
// sign or edges). Defaults to "center" when a category is not listed.
export const CATEGORY_IMAGE_POS: Record<string, string> = {
  sandwiches: "center 78%",
  burgers: "center 50%",
  pancakes: "center 55%",
  tostas: "center 62%",
  pulgas: "center 50%",
  bocadillos: "center 55%",
  ensaladas: "center 50%",
  picoteo: "center 55%",
  cocteles: "center 45%",
  cerveza: "center 50%",
  cafe: "center 55%",
  zumos: "center 42%",
  refrescos: "center 50%",
  brunch: "center 45%",
  desayunos: "center 50%",
};

/* =============================== ESPAÑOL =============================== */

export const CARTA_ES: Category[] = [
  {
    id: "brunch",
    title: "Brunch",
    note: "Disponibles hasta las 14:00. Incluyen yogur griego con granola, frutas frescas y sirope de agave, café o té, zumo de naranja pequeño o cóctel mimosa.",
    dishes: [
      { name: "Huevos Benedict", price: "14,95 €", note: "Con salsa holandesa; a elegir salmón, beicon o aguacate." },
      { name: "Huevos revueltos", price: "14,95 €", note: "Con tostadas y ensalada; a elegir salmón, beicon, aguacate, champiñones o jamón serrano." },
      { name: "Bagels", price: "14,95 €", note: "Con rúcula, queso crema y aguacate; a elegir salmón, beicon, champiñones o jamón serrano." },
      { name: "Pancakes", price: "14,95 €", note: "Con beicon, 2 huevos fritos, sirope de arce y tomates cherry." },
      { name: "Tostas", price: "14,95 €", note: "Pan de masa madre con huevos revueltos y aguacate; a elegir beicon, salmón o champiñones." },
      { name: "Tosta Serrano y Manchego", price: "14,95 €", note: "Sándwich de masa madre con jamón serrano y queso manchego." },
      { name: "Continental para 2 personas", price: "32,00 €", note: "Salmón, embutidos y quesos variados, huevos revueltos, tumaca y aguacate, variedad de panes y croissants." },
    ],
  },
  {
    id: "desayunos",
    title: "Desayunos",
    dishes: [
      { name: "Huevos revueltos clásicos", price: "4,00 €" },
      { name: "Huevos revueltos con beicon o jamón serrano", price: "7,50 €" },
      { name: "Huevos revueltos con salmón o jamón ibérico", price: "8,50 €" },
      { name: "Huevos Benedict con aguacate", price: "9,50 €", note: "Huevo poché sobre pan brioche, salsa holandesa, rúcula y sésamo negro. Hasta las 14:00." },
      { name: "Huevos Benedict con beicon", price: "9,00 €" },
      { name: "Huevos Benedict con salmón", price: "9,50 €" },
      { name: "Huevos Turcos", price: "7,00 €", note: "Yogur griego, ajo, copos de chile, mantequilla de pimentón, zaatar, dos huevos escalfados y tostadas." },
      { name: "Tortilla francesa", price: "6,00 €", note: "Con jamón y queso." },
      { name: "Desayuno inglés", price: "8,90 €", note: "2 huevos fritos, salchichas, beans, champiñones, beicon y tostadas." },
    ],
  },
  {
    id: "pancakes",
    title: "Pancakes",
    dishes: [
      { name: "Con sirope de arce", price: "8,00 €" },
      { name: "Con sirope de agave y frutas", price: "8,00 €" },
      { name: "Con Nutella", price: "8,00 €" },
      { name: "Con dulce de leche", price: "8,00 €" },
      { name: "Con crema de pistacho", price: "8,00 €" },
      { name: "Extra helado", price: "2,00 €" },
      { name: "Extra frutas", price: "2,00 €" },
      { name: "Extra nata", price: "1,00 €" },
    ],
  },
  {
    id: "tostas",
    title: "Tostas",
    note: "Extras: huevo poché 1 € · aguacate 2,80 € · salmón 2,80 € · beicon 1,50 € · champiñones 1,50 € · ibérico 2,80 € · manchego 1,50 € · jamón serrano 1,50 €.",
    dishes: [
      { name: "Tostada", price: "2,50 €", note: "Mermelada y mantequilla." },
      { name: "Tostada de pan baguette", price: "3,00 € – 3,50 €", note: "Mermelada y mantequilla, o aceite y tumaca." },
      { name: "Tostada de pan pulga", price: "2,70 € – 3,00 €", note: "Mermelada y mantequilla, o aceite y tumaca." },
      { name: "Queso de cabra", price: "8,00 €", note: "Queso de cabra, tomate cherry asado, hierbas, rúcula y crema de balsámico. En pan de masa madre." },
      { name: "Burrata", price: "9,20 €", note: "Burrata, rúcula, tomate cherry asado, salsa de albahaca y balsámico." },
      { name: "Classic", price: "8,00 € – 9,00 €", note: "Beicon o salmón, aguacate, huevos revueltos, rúcula y sésamo negro." },
      { name: "Meli Melo", price: "8,00 €", note: "Rulo de cabra, miel y nueces." },
      { name: "Champiñones", price: "8,90 €", note: "Champiñones, manchego, cebolla caramelizada y rúcula." },
      { name: "La Catalana", price: "8,90 €", note: "Jamón ibérico, tumaca y aceite de oliva." },
      { name: "Queso crema", price: "7,60 €", note: "Queso crema y aguacate. Extra huevo poché +1 €." },
      { name: "Queso feta", price: "9,20 €", note: "Feta, pesto de almendras, cherry asado, jamón serrano, aceitunas negras y rúcula." },
    ],
  },
  {
    id: "croissants",
    title: "Croissants de mantequilla",
    dishes: [
      { name: "Croissant", price: "3,30 €", note: "Mermelada y mantequilla." },
      { name: "Croissant mixto", price: "3,50 €", note: "Jamón dulce y queso." },
      { name: "Croissant de pollo", price: "5,40 €", note: "Pollo desmenuzado, queso, mayonesa, tomate y lechuga." },
      { name: "Croissant de salmón", price: "6,00 €", note: "Salmón, queso blanco fresco y aguacate." },
      { name: "Croissant de Nutella", price: "3,50 €" },
    ],
  },
  {
    id: "bagels",
    title: "Bagels",
    dishes: [
      { name: "Nórdico", price: "8,90 €", note: "Salmón ahumado, queso crema, aguacate, rúcula y pepino." },
      { name: "Atún", price: "8,00 €", note: "Atún, mayonesa, lechuga y alcaparras." },
      { name: "Americano", price: "7,90 €", note: "Beicon, queso crema y huevos revueltos." },
      { name: "Ibérico", price: "8,90 €", note: "Jamón ibérico, huevo frito y tomate." },
      { name: "Pavo", price: "6,50 €", note: "Pavo, queso crema, rúcula y tomate." },
    ],
  },
  {
    id: "bocadillos",
    title: "Bocadillos",
    dishes: [
      { name: "Atún", price: "5,50 €", note: "Atún, mayonesa, tomate y lechuga." },
      { name: "BLT", price: "5,00 €", note: "Beicon, lechuga, tomate y mayonesa." },
      { name: "Pata", price: "5,50 €", note: "Pata, queso de cabra, tomate y AOVE." },
      { name: "El San Blas", price: "6,20 €", note: "A elegir pollo, ternera o lomo; salsa de aguacate, beicon, queso, huevo, lechuga y tomate." },
      { name: "Lomo / Ternera", price: "5,10 €", note: "Lechuga, tomate, mayonesa y queso." },
      { name: "Americano", price: "5,50 €", note: "Jamón dulce, beicon, queso, mayonesa, huevo, lechuga y tomate." },
      { name: "Pollo", price: "5,10 €", note: "Pollo, queso, lechuga y tomate." },
      { name: "Pollo desmenuzado", price: "5,10 €", note: "Lechuga, tomate, mayonesa y queso." },
      { name: "El Francés", price: "4,90 €", note: "Tortilla francesa." },
    ],
  },
  {
    id: "pulgas",
    title: "Pulgas",
    note: "Pan a elegir: normal o de semillas. Extras: aguacate 1 € · queso manchego 1 €.",
    dishes: [
      { name: "Clásicas", price: "3,20 €", note: "Lechuga, tomate y mayonesa; a escoger beicon, pollo desmenuzado, ternera, lomo o atún." },
      { name: "Queso blanco / pavo / pata", price: "3,20 €", note: "Queso blanco y tomate; pavo, queso blanco y tomate; o pata, queso de cabra y tomate." },
      { name: "Jamón serrano", price: "3,20 €", note: "Jamón serrano y tumaca." },
      { name: "Salmón", price: "3,70 €", note: "Salmón, queso crema y rúcula." },
      { name: "Pulga sin gluten", price: "Consultar", note: "Pregunta por disponibilidad. Extra +1 €." },
    ],
  },
  {
    id: "sandwiches",
    title: "Sándwiches",
    dishes: [
      { name: "Mixto", price: "3,00 €", note: "Jamón dulce, queso y mantequilla." },
      { name: "Americano", price: "5,00 €", note: "Jamón dulce, beicon, queso, mayonesa, tomate, lechuga y huevo." },
      { name: "Pollo", price: "5,00 €", note: "Pollo desmenuzado, queso, lechuga, tomate y mayonesa." },
      { name: "Atún", price: "5,00 €", note: "Atún, lechuga, tomate, cebolla y mayonesa." },
      { name: "Nuestro Club Sandwich", price: "8,90 €", note: "Pollo desmenuzado, beicon, queso, salsa de aguacate, huevo duro, tomate y lechuga. Con papas fritas." },
    ],
  },
  {
    id: "bowls",
    title: "Bowls y yogures",
    dishes: [
      { name: "Yogur bowl", price: "7,90 €", note: "Yogur griego, frutas frescas, granola y sirope de agave." },
      { name: "Yogur chía bowl", price: "8,00 €", note: "Yogur griego, chía, frutas frescas y sirope de agave." },
      { name: "Açaí frozen", price: "11,50 €", note: "Guaraná, frutas frescas, granola, coco rallado y semillas." },
      { name: "Extra mantequilla de cacahuete", price: "1,50 €" },
    ],
  },
  {
    id: "burgers",
    title: "Burgers",
    note: "Disponibles a partir de las 12:00. Todas de carne 100 % ternera (excepto la vegana) y con papas fritas, salvo indicación. Extras: huevo 1 € · boniato 1 €.",
    dishes: [
      { name: "Cheeseburger", price: "8,00 €", note: "Cheddar." },
      { name: "La Doble", price: "15,90 €", note: "320 g de carne 100 % ternera, doble cheddar, beicon y salsa de la casa." },
      { name: "Americana", price: "12,90 €", note: "Beicon, huevo, cheddar, lechuga, tomate y pepinillos." },
      { name: "Mexicana", price: "11,90 €", note: "Cheddar, guacamole, lechuga, tomate y jalapeños." },
      { name: "La Dulce", price: "12,90 €", note: "Brie, cebolla caramelizada, lechuga y tomate." },
      { name: "Smash Brioche", price: "12,90 €", note: "Doble smash, doble cheddar, salsa casera, lechuga y tomate." },
      { name: "Wilder Brioche", price: "13,90 €", note: "Cheddar, tomate cherry asado, huevo frito, lechuga y salsa de aguacate. Incluye papas de boniato." },
      { name: "Queso de cabra", price: "13,90 €", note: "Rulo de cabra, cebolla caramelizada, salsa casera, lechuga y tomate." },
      { name: "Vegan HEÜRA Brioche", price: "13,90 €", note: "Proteína vegetal HEÜRA, cebolla, tomate, lechuga y aguacate." },
    ],
  },
  {
    id: "ensaladas",
    title: "Ensaladas",
    note: "Extra pan 1,50 €.",
    dishes: [
      { name: "César", price: "10,50 €", note: "Pollo, lechuga, salsa César, croutons, parmesano y tomates cherry." },
      { name: "Manzana", price: "12,50 €", note: "Manzana, nueces, rúcula, espinacas, queso blanco fresco y vinagreta de miel." },
      { name: "Burrata", price: "11,50 €", note: "Tomate cherry, burrata, aceite de albahaca y crema de balsámico." },
      { name: "Griega", price: "10,50 €", note: "Feta, aceitunas kalamata, pepino, tomate, cebolla roja, pimiento y salsa de yogur." },
      { name: "La Dulce", price: "12,50 €", note: "Espinaca, huevo duro, tomate cherry, feta, salmón ahumado y quinoa." },
      { name: "La Clásica", price: "12,00 €", note: "Lechuga, tomate, cebolla, atún, pepino, aguacate, pimiento y huevo duro." },
    ],
  },
  {
    id: "platos",
    title: "Platos",
    dishes: [
      { name: "Lasaña de carne", price: "9,00 €" },
      { name: "Tortilla La Dulce", price: "11,90 €", note: "Tortilla de papas y calabacín con granos de amapola, aguacate y rúcula." },
      { name: "Pechuga de pollo", price: "8,00 €", note: "Con papas fritas y ensalada." },
      { name: "Lomo", price: "8,00 €", note: "Lomo con huevo frito, papas fritas y ensalada." },
    ],
  },
  {
    id: "picoteo",
    title: "Picoteo",
    dishes: [
      { name: "Nachos", price: "11,00 €", note: "Totopos, queso cheddar, pico de gallo, guacamole, jalapeños y crema agria." },
      { name: "Huevos rotos", price: "12,00 €", note: "Jamón ibérico, papas fritas y huevos fritos." },
      { name: "Croquetas", price: "6,50 €", note: "Croquetas de jamón con su alioli." },
      { name: "Tabla", price: "15,00 €", note: "Jamón ibérico, queso manchego y pan." },
      { name: "Jalapeño Peppers", price: "6,50 €", note: "5 jalapeños rellenos de cheddar y su salsa." },
      { name: "Fingers de pollo", price: "8,00 €", note: "5 fingers de pollo con salsa de mostaza y miel." },
      { name: "Alitas de pollo", price: "6,50 €" },
    ],
  },
  {
    id: "papas",
    title: "Papas",
    dishes: [
      { name: "Papas fritas", price: "3,70 €" },
      { name: "Papas locas", price: "6,90 €", note: "Con jamón, queso cheddar, gouda y sus salsas." },
      { name: "Fritas de boniato", price: "6,90 €", note: "Con parmesano y ajo, o con salsa de yogur." },
    ],
  },
  {
    id: "postres",
    title: "Postres",
    dishes: [
      { name: "Croissant", price: "2,00 €" },
      { name: "Bretzel de almendra", price: "2,90 €" },
      { name: "Caracola", price: "2,50 €" },
      { name: "Palmera", price: "3,50 €" },
      { name: "Napolitana", price: "2,00 €" },
      { name: "Croissant relleno", price: "5,00 €" },
      { name: "Milhojas", price: "2,20 €" },
      { name: "Milhojas de merengue", price: "3,00 €" },
      { name: "Petit suisse (éclair)", price: "2,20 €" },
      { name: "Hojaldre de fresa", price: "4,00 €" },
      { name: "Hojaldre de frutas", price: "4,00 €" },
      { name: "Hojaldre de manzana", price: "2,90 €" },
      { name: "Barquita de queso", price: "2,90 €" },
      { name: "Barquita de frutos secos", price: "2,90 €" },
      { name: "Tartaleta de fresa o frutas", price: "3,00 €" },
      { name: "Cuña", price: "2,50 €" },
      { name: "Gofre", price: "5,50 €" },
      { name: "Tarta de manzana", price: "4,50 €" },
      { name: "Tartas (por porción)", price: "5,00 €" },
      { name: "Brownie sin gluten", price: "4,00 €" },
    ],
  },
  {
    id: "zumos",
    title: "Zumos naturales",
    dishes: [
      { name: "Naranja (pequeño / grande)", price: "2,30 € / 3,90 €" },
      { name: "Zumo combinado (1 / 2 / 3 frutas)", price: "3,50 € / 4,50 € / 5,00 €" },
      { name: "El Rojo / El Verde / El Fresco / El Uno", price: "4,50 €" },
      { name: "Extra de fruta", price: "0,50 €" },
    ],
  },
  {
    id: "batidos",
    title: "Batidos",
    note: "Leche vegetal a elegir: avena, soja o sin lactosa.",
    dishes: [
      { name: "Batido (1 / 2 / 3 frutas)", price: "3,80 € / 4,80 € / 5,80 €" },
      { name: "Extra de fruta", price: "0,50 €" },
      { name: "Extra de leche vegetal", price: "0,50 €" },
    ],
  },
  {
    id: "cafe",
    title: "Café",
    note: "Extras: leche vegetal 0,20 € · leche 0,20 € – 0,50 € · hielo 0,10 € · nata 0,50 € · para llevar 0,10 €.",
    dishes: [
      { name: "Espresso", price: "1,15 €" },
      { name: "Doble espresso", price: "2,00 €" },
      { name: "Descafeinado (máquina o sobre)", price: "1,20 €" },
      { name: "Cortado natural", price: "1,50 €" },
      { name: "Cortado largo", price: "1,70 €" },
      { name: "Cortado L/L", price: "1,50 €" },
      { name: "Cortado condensada", price: "1,50 €" },
      { name: "Leche y leche largo", price: "1,80 €" },
      { name: "Café con leche", price: "1,70 €" },
      { name: "Café con leche grande", price: "2,50 €" },
      { name: "Americano", price: "1,30 €" },
      { name: "Cappuccino", price: "2,00 €" },
      { name: "Carajillo", price: "1,60 €" },
      { name: "Barraquito con licor", price: "2,50 €" },
      { name: "Ice latte", price: "3,00 €" },
      { name: "Ice latte Nutella", price: "3,90 €" },
      { name: "Irish coffee", price: "5,10 €" },
      { name: "Café frappé", price: "4,10 €" },
      { name: "Té o infusiones", price: "1,60 €" },
      { name: "Té matcha con naranja", price: "5,00 €" },
      { name: "Té matcha (agua / leche / leche vegetal)", price: "3,00 € / 3,50 € / 3,50 €" },
      { name: "Chocolate caliente a la taza", price: "2,60 €" },
      { name: "ColaCao", price: "2,00 €" },
    ],
  },
  {
    id: "refrescos",
    title: "Refrescos",
    dishes: [
      { name: "Sprite / Coca-Cola / Coca-Cola Zero / Fanta", price: "2,20 €" },
      { name: "Clipper", price: "1,80 €" },
      { name: "Appletizer", price: "2,20 €" },
      { name: "Schweppes Limón", price: "2,00 €" },
      { name: "Nestea / Aquarius", price: "2,20 €" },
      { name: "Monster", price: "2,90 €" },
      { name: "Tónica", price: "1,90 €" },
      { name: "Agua con gas", price: "1,50 €" },
      { name: "Agua (pequeña / grande)", price: "1,20 € / 2,20 €" },
    ],
  },
  {
    id: "cerveza",
    title: "Cerveza",
    dishes: [
      { name: "Tacoa (artesana canaria)", price: "3,90 €" },
      { name: "Caña / jarra", price: "1,50 € / 3,00 €" },
      { name: "Caña clarita / jarra", price: "1,80 € / 3,60 €" },
      { name: "Turia (caña / jarra)", price: "1,80 € / 3,60 €" },
      { name: "Turia (botella)", price: "2,20 €" },
      { name: "Dorada Pilsen", price: "1,80 €" },
      { name: "Dorada Especial", price: "2,00 €" },
      { name: "Heineken", price: "1,90 €" },
      { name: "Corona", price: "2,50 €" },
      { name: "1906", price: "2,30 €" },
      { name: "Estrella Galicia", price: "2,30 €" },
      { name: "Estrella Damm", price: "1,70 €" },
      { name: "Voll-Damm", price: "2,30 €" },
      { name: "Damm Lemon (clara)", price: "1,90 €" },
      { name: "Free Damm (sin alcohol, sin gluten)", price: "1,80 €" },
      { name: "Free Damm Lemon (sin alcohol, sin gluten)", price: "1,90 €" },
      { name: "Heineken sin alcohol", price: "2,10 €" },
      { name: "Corona sin alcohol", price: "2,20 €" },
      { name: "Daura (sin gluten)", price: "2,20 €" },
    ],
  },
  {
    id: "vino",
    title: "Vino",
    dishes: [
      { name: "Cava Codorníu Benjamín", price: "4,50 €" },
      { name: "Tinto de verano", price: "3,50 €" },
      { name: "Tinto (copa / botella)", price: "2,80 € / 14,00 €" },
      { name: "Rosado (copa / botella)", price: "3,50 € / 18,00 €" },
      { name: "Blanco seco (copa / botella)", price: "2,80 € / 14,00 €" },
      { name: "Blanco afrutado (copa / botella)", price: "3,50 € / 18,00 €" },
      { name: "Sangría (50 cl / 1 L)", price: "8,00 € / 15,00 €" },
    ],
  },
  {
    id: "sidra",
    title: "Sidra",
    dishes: [
      { name: "Olde English (grifo, 25 cl / jarra)", price: "2,50 € / 5,00 €" },
      { name: "Kopparberg", price: "3,50 €" },
    ],
  },
  {
    id: "cocteles",
    title: "Cócteles",
    dishes: [
      { name: "Piña Colada", price: "7,00 €" },
      { name: "Daiquiri Frozen", price: "7,00 €" },
      { name: "Mojito (clásico / frutas)", price: "6,50 € / 7,00 €" },
      { name: "Mojito sin alcohol", price: "4,50 €" },
      { name: "Margarita (clásico / frozen de fresa)", price: "6,50 €" },
      { name: "Mimosa", price: "3,00 €" },
      { name: "Aperol Spritz", price: "7,00 €" },
      { name: "Campari Spritz", price: "7,00 €" },
      { name: "Negroni", price: "5,50 €" },
      { name: "Caipirinha", price: "7,00 €" },
      { name: "Caipiroska", price: "7,00 €" },
      { name: "Long Island", price: "7,00 €" },
      { name: "Sex on the Beach", price: "7,00 €" },
      { name: "Martini Pornstar", price: "7,00 €" },
      { name: "Tequila Sunrise", price: "7,00 €" },
      { name: "Espresso Martini", price: "7,00 €" },
    ],
  },
  {
    id: "vodka",
    title: "Vodka",
    dishes: [
      { name: "Smirnoff", price: "3,80 €" },
      { name: "Absolut", price: "4,00 €" },
      { name: "Black", price: "4,00 €" },
    ],
  },
  {
    id: "licores",
    title: "Licores",
    dishes: [
      { name: "Baileys", price: "4,00 €" },
      { name: "Amaretto", price: "3,50 €" },
      { name: "Variados", price: "3,50 €" },
    ],
  },
  {
    id: "vermut",
    title: "Vermut",
    dishes: [
      { name: "Martini", price: "3,50 €" },
      { name: "Campari", price: "3,50 €" },
      { name: "Aperol", price: "3,50 €" },
    ],
  },
  {
    id: "gin",
    title: "Gin",
    dishes: [
      { name: "Seagram's", price: "4,60 €" },
      { name: "Gordon's", price: "4,60 €" },
      { name: "Beefeater", price: "4,60 €" },
      { name: "Macaronesian", price: "5,60 €" },
      { name: "Puerto de Indias", price: "5,60 €" },
      { name: "Tanqueray", price: "5,60 €" },
      { name: "Bombay Sapphire", price: "7,50 €" },
    ],
  },
  {
    id: "ron",
    title: "Ron",
    dishes: [
      { name: "Arehucas Amarillo", price: "3,50 €" },
      { name: "Havana 7", price: "3,80 €" },
      { name: "Bacardí", price: "3,80 €" },
      { name: "Legendario", price: "3,80 €" },
    ],
  },
  {
    id: "tequila",
    title: "Tequila",
    dishes: [
      { name: "Tequila (rosa / mango / limón)", price: "3,50 €" },
    ],
  },
  {
    id: "brandy",
    title: "Brandy",
    dishes: [
      { name: "Veterano", price: "3,00 €" },
      { name: "Magno", price: "3,20 €" },
      { name: "Rémy Martin", price: "4,00 €" },
    ],
  },
  {
    id: "chupitos",
    title: "Chupitos",
    dishes: [
      { name: "Variados", price: "2,00 € / 2,50 €" },
      { name: "Chupito de whisky", price: "3,00 €" },
    ],
  },
  {
    id: "whisky",
    title: "Whisky",
    dishes: [
      { name: "JB", price: "4,00 €" },
      { name: "Ballantine's", price: "4,00 €" },
      { name: "Johnnie Walker Red", price: "4,00 €" },
      { name: "Macallan", price: "4,50 €" },
      { name: "Jack Daniel's", price: "5,00 €" },
      { name: "Johnnie Walker Black", price: "5,00 €" },
      { name: "Glenfiddich 12", price: "5,00 €" },
      { name: "Jameson", price: "5,00 €" },
    ],
  },
];

/* =============================== ENGLISH =============================== */

export const CARTA_EN: Category[] = [
  {
    id: "brunch",
    title: "Brunch",
    note: "Available until 14:00. Each brunch includes Greek yogurt with granola, fresh fruit and agave syrup, coffee or tea, a small orange juice or a mimosa cocktail.",
    dishes: [
      { name: "Eggs Benedict", price: "€14.95", note: "With hollandaise; choose salmon, bacon or avocado." },
      { name: "Scrambled eggs", price: "€14.95", note: "With toast and salad; choose salmon, bacon, avocado, mushrooms or Serrano ham." },
      { name: "Bagels", price: "€14.95", note: "With rocket, cream cheese and avocado; choose salmon, bacon, mushrooms or Serrano ham." },
      { name: "Pancakes", price: "€14.95", note: "With bacon, 2 fried eggs, maple syrup and cherry tomatoes." },
      { name: "Toast", price: "€14.95", note: "Sourdough with scrambled eggs and avocado; choose bacon, salmon or mushrooms." },
      { name: "Serrano & Manchego toast", price: "€14.95", note: "Sourdough sandwich with Serrano ham and Manchego cheese." },
      { name: "Continental for 2", price: "€32.00", note: "Salmon, cured meats and assorted cheeses, scrambled eggs, tumaca and avocado, a selection of breads and croissants." },
    ],
  },
  {
    id: "desayunos",
    title: "Breakfast",
    dishes: [
      { name: "Classic scrambled eggs", price: "€4.00" },
      { name: "Scrambled eggs with bacon or Serrano ham", price: "€7.50" },
      { name: "Scrambled eggs with salmon or Iberian ham", price: "€8.50" },
      { name: "Eggs Benedict with avocado", price: "€9.50", note: "Poached egg on brioche, hollandaise, rocket and black sesame. Until 14:00." },
      { name: "Eggs Benedict with bacon", price: "€9.00" },
      { name: "Eggs Benedict with salmon", price: "€9.50" },
      { name: "Turkish eggs", price: "€7.00", note: "Greek yogurt, garlic, chilli flakes, paprika butter, za'atar, two poached eggs and toast." },
      { name: "French omelette", price: "€6.00", note: "With ham and cheese." },
      { name: "English breakfast", price: "€8.90", note: "2 fried eggs, sausages, beans, mushrooms, bacon and toast." },
    ],
  },
  {
    id: "pancakes",
    title: "Pancakes",
    dishes: [
      { name: "With maple syrup", price: "€8.00" },
      { name: "With agave syrup and fruit", price: "€8.00" },
      { name: "With Nutella", price: "€8.00" },
      { name: "With dulce de leche", price: "€8.00" },
      { name: "With pistachio cream", price: "€8.00" },
      { name: "Extra ice cream", price: "€2.00" },
      { name: "Extra fruit", price: "€2.00" },
      { name: "Extra whipped cream", price: "€1.00" },
    ],
  },
  {
    id: "tostas",
    title: "Toasts",
    note: "Extras: poached egg €1 · avocado €2.80 · salmon €2.80 · bacon €1.50 · mushrooms €1.50 · Iberian ham €2.80 · Manchego €1.50 · Serrano ham €1.50.",
    dishes: [
      { name: "Toast", price: "€2.50", note: "Jam and butter." },
      { name: "Baguette toast", price: "€3.00 – €3.50", note: "Jam and butter, or oil and tumaca." },
      { name: "Pulga-bread toast", price: "€2.70 – €3.00", note: "Jam and butter, or oil and tumaca." },
      { name: "Goat cheese", price: "€8.00", note: "Goat cheese, roasted cherry tomato, herbs, rocket and balsamic cream. On sourdough." },
      { name: "Burrata", price: "€9.20", note: "Burrata, rocket, roasted cherry tomato, basil sauce and balsamic." },
      { name: "Classic", price: "€8.00 – €9.00", note: "Bacon or salmon, avocado, scrambled eggs, rocket and black sesame." },
      { name: "Meli Melo", price: "€8.00", note: "Goat cheese log, honey and walnuts." },
      { name: "Mushrooms", price: "€8.90", note: "Mushrooms, Manchego, caramelised onion and rocket." },
      { name: "La Catalana", price: "€8.90", note: "Iberian ham, tumaca and olive oil." },
      { name: "Cream cheese", price: "€7.60", note: "Cream cheese and avocado. Add poached egg +€1." },
      { name: "Feta cheese", price: "€9.20", note: "Feta, almond pesto, roasted cherry, Serrano ham, black olives and rocket." },
    ],
  },
  {
    id: "croissants",
    title: "Butter croissants",
    dishes: [
      { name: "Croissant", price: "€3.30", note: "Jam and butter." },
      { name: "Mixed croissant", price: "€3.50", note: "Ham and cheese." },
      { name: "Chicken croissant", price: "€5.40", note: "Shredded chicken, cheese, mayo, tomato and lettuce." },
      { name: "Salmon croissant", price: "€6.00", note: "Salmon, fresh white cheese and avocado." },
      { name: "Nutella croissant", price: "€3.50" },
    ],
  },
  {
    id: "bagels",
    title: "Bagels",
    dishes: [
      { name: "Nordic", price: "€8.90", note: "Smoked salmon, cream cheese, avocado, rocket and cucumber." },
      { name: "Tuna", price: "€8.00", note: "Tuna, mayo, lettuce and capers." },
      { name: "American", price: "€7.90", note: "Bacon, cream cheese and scrambled eggs." },
      { name: "Iberian", price: "€8.90", note: "Iberian ham, fried egg and tomato." },
      { name: "Turkey", price: "€6.50", note: "Turkey, cream cheese, rocket and tomato." },
    ],
  },
  {
    id: "bocadillos",
    title: "Baguette sandwiches",
    dishes: [
      { name: "Tuna", price: "€5.50", note: "Tuna, mayo, tomato and lettuce." },
      { name: "BLT", price: "€5.00", note: "Bacon, lettuce, tomato and mayo." },
      { name: "Pata", price: "€5.50", note: "Cured pork, goat cheese, tomato and olive oil." },
      { name: "El San Blas", price: "€6.20", note: "Choose chicken, veal or loin; avocado sauce, bacon, cheese, egg, lettuce and tomato." },
      { name: "Loin / Veal", price: "€5.10", note: "Lettuce, tomato, mayo and cheese." },
      { name: "American", price: "€5.50", note: "Ham, bacon, cheese, mayo, egg, lettuce and tomato." },
      { name: "Chicken", price: "€5.10", note: "Chicken, cheese, lettuce and tomato." },
      { name: "Shredded chicken", price: "€5.10", note: "Lettuce, tomato, mayo and cheese." },
      { name: "El Francés", price: "€4.90", note: "French omelette." },
    ],
  },
  {
    id: "pulgas",
    title: "Pulga rolls",
    note: "Choose your bread: plain or seeded. Extras: avocado €1 · Manchego cheese €1.",
    dishes: [
      { name: "Classic", price: "€3.20", note: "Lettuce, tomato and mayo; choose bacon, shredded chicken, veal, loin or tuna." },
      { name: "White cheese / turkey / pata", price: "€3.20", note: "White cheese and tomato; turkey, white cheese and tomato; or cured pork, goat cheese and tomato." },
      { name: "Serrano ham", price: "€3.20", note: "Serrano ham and tumaca." },
      { name: "Salmon", price: "€3.70", note: "Salmon, cream cheese and rocket." },
      { name: "Gluten-free pulga", price: "Ask us", note: "Subject to availability. Extra +€1." },
    ],
  },
  {
    id: "sandwiches",
    title: "Sandwiches",
    dishes: [
      { name: "Mixed", price: "€3.00", note: "Ham, cheese and butter." },
      { name: "American", price: "€5.00", note: "Ham, bacon, cheese, mayo, tomato, lettuce and egg." },
      { name: "Chicken", price: "€5.00", note: "Shredded chicken, cheese, lettuce, tomato and mayo." },
      { name: "Tuna", price: "€5.00", note: "Tuna, lettuce, tomato, onion and mayo." },
      { name: "Our Club Sandwich", price: "€8.90", note: "Shredded chicken, bacon, cheese, avocado sauce, hard-boiled egg, tomato and lettuce. With fries." },
    ],
  },
  {
    id: "bowls",
    title: "Bowls & yogurts",
    dishes: [
      { name: "Yogurt bowl", price: "€7.90", note: "Greek yogurt, fresh fruit, granola and agave syrup." },
      { name: "Chia yogurt bowl", price: "€8.00", note: "Greek yogurt, chia, fresh fruit and agave syrup." },
      { name: "Açaí frozen", price: "€11.50", note: "Guaraná, fresh fruit, granola, grated coconut and seeds." },
      { name: "Extra peanut butter", price: "€1.50" },
    ],
  },
  {
    id: "burgers",
    title: "Burgers",
    note: "Available from 12:00. All 100% beef (except the vegan one) and served with fries unless stated. Extras: egg €1 · sweet potato €1.",
    dishes: [
      { name: "Cheeseburger", price: "€8.00", note: "Cheddar." },
      { name: "La Doble", price: "€15.90", note: "320g of 100% beef, double cheddar, bacon and house sauce." },
      { name: "American", price: "€12.90", note: "Bacon, egg, cheddar, lettuce, tomato and pickles." },
      { name: "Mexican", price: "€11.90", note: "Cheddar, guacamole, lettuce, tomato and jalapeños." },
      { name: "La Dulce", price: "€12.90", note: "Brie, caramelised onion, lettuce and tomato." },
      { name: "Smash Brioche", price: "€12.90", note: "Double smash, double cheddar, house sauce, lettuce and tomato." },
      { name: "Wilder Brioche", price: "€13.90", note: "Cheddar, roasted cherry tomato, fried egg, lettuce and avocado sauce. Includes sweet potato fries." },
      { name: "Goat cheese", price: "€13.90", note: "Goat cheese log, caramelised onion, house sauce, lettuce and tomato." },
      { name: "Vegan HEÜRA Brioche", price: "€13.90", note: "HEÜRA plant protein, onion, tomato, lettuce and avocado." },
    ],
  },
  {
    id: "ensaladas",
    title: "Salads",
    note: "Extra bread €1.50.",
    dishes: [
      { name: "Caesar", price: "€10.50", note: "Chicken, lettuce, Caesar dressing, croutons, parmesan and cherry tomatoes." },
      { name: "Apple", price: "€12.50", note: "Apple, walnuts, rocket, spinach, fresh white cheese and honey vinaigrette." },
      { name: "Burrata", price: "€11.50", note: "Cherry tomato, burrata, basil oil and balsamic cream." },
      { name: "Greek", price: "€10.50", note: "Feta, kalamata olives, cucumber, tomato, red onion, pepper and yogurt sauce." },
      { name: "La Dulce", price: "€12.50", note: "Spinach, hard-boiled egg, cherry tomato, feta, smoked salmon and quinoa." },
      { name: "La Clásica", price: "€12.00", note: "Lettuce, tomato, onion, tuna, cucumber, avocado, pepper and hard-boiled egg." },
    ],
  },
  {
    id: "platos",
    title: "Mains",
    dishes: [
      { name: "Meat lasagne", price: "€9.00" },
      { name: "La Dulce omelette", price: "€11.90", note: "Potato and courgette omelette with poppy seeds, avocado and rocket." },
      { name: "Chicken breast", price: "€8.00", note: "With fries and salad." },
      { name: "Loin", price: "€8.00", note: "Loin with fried egg, fries and salad." },
    ],
  },
  {
    id: "picoteo",
    title: "Sharing & snacks",
    dishes: [
      { name: "Nachos", price: "€11.00", note: "Tortilla chips, cheddar, pico de gallo, guacamole, jalapeños and sour cream." },
      { name: "Broken eggs", price: "€12.00", note: "Iberian ham, fries and fried eggs." },
      { name: "Croquettes", price: "€6.50", note: "Ham croquettes with aioli." },
      { name: "Board", price: "€15.00", note: "Iberian ham, Manchego cheese and bread." },
      { name: "Jalapeño Peppers", price: "€6.50", note: "5 cheddar-stuffed jalapeños with sauce." },
      { name: "Chicken fingers", price: "€8.00", note: "5 chicken fingers with honey mustard sauce." },
      { name: "Chicken wings", price: "€6.50" },
    ],
  },
  {
    id: "papas",
    title: "Fries",
    dishes: [
      { name: "French fries", price: "€3.70" },
      { name: "Crazy fries", price: "€6.90", note: "With ham, cheddar, gouda and sauces." },
      { name: "Sweet potato fries", price: "€6.90", note: "With parmesan and garlic, or with yogurt sauce." },
    ],
  },
  {
    id: "postres",
    title: "Desserts",
    dishes: [
      { name: "Croissant", price: "€2.00" },
      { name: "Almond pretzel", price: "€2.90" },
      { name: "Cinnamon swirl pastry", price: "€2.50" },
      { name: "Palmier pastry", price: "€3.50" },
      { name: "Pain au chocolat", price: "€2.00" },
      { name: "Filled croissant", price: "€5.00" },
      { name: "Mille-feuille", price: "€2.20" },
      { name: "Meringue mille-feuille", price: "€3.00" },
      { name: "Éclair", price: "€2.20" },
      { name: "Strawberry puff pastry", price: "€4.00" },
      { name: "Fruit puff pastry", price: "€4.00" },
      { name: "Apple puff pastry", price: "€2.90" },
      { name: "Cheese tartlet", price: "€2.90" },
      { name: "Nut tartlet", price: "€2.90" },
      { name: "Strawberry or fruit tartlet", price: "€3.00" },
      { name: "Cream-filled pastry slice", price: "€2.50" },
      { name: "Waffle", price: "€5.50" },
      { name: "Apple pie", price: "€4.50" },
      { name: "Cakes (per slice)", price: "€5.00" },
      { name: "Gluten-free brownie", price: "€4.00" },
    ],
  },
  {
    id: "zumos",
    title: "Natural juices",
    dishes: [
      { name: "Orange (small / large)", price: "€2.30 / €3.90" },
      { name: "Combined juice (1 / 2 / 3 fruits)", price: "€3.50 / €4.50 / €5.00" },
      { name: "The Red / Green / Fresh / The One", price: "€4.50" },
      { name: "Extra fruit", price: "€0.50" },
    ],
  },
  {
    id: "batidos",
    title: "Smoothies",
    note: "Plant milk of your choice: oat, soy or lactose-free.",
    dishes: [
      { name: "Smoothie (1 / 2 / 3 fruits)", price: "€3.80 / €4.80 / €5.80" },
      { name: "Extra fruit", price: "€0.50" },
      { name: "Extra plant milk", price: "€0.50" },
    ],
  },
  {
    id: "cafe",
    title: "Coffee",
    note: "Extras: plant milk €0.20 · milk €0.20 – €0.50 · ice €0.10 · cream €0.50 · takeaway €0.10.",
    dishes: [
      { name: "Espresso", price: "€1.15" },
      { name: "Double espresso", price: "€2.00" },
      { name: "Decaf (machine or sachet)", price: "€1.20" },
      { name: "Cortado natural", price: "€1.50" },
      { name: "Cortado largo", price: "€1.70" },
      { name: "Cortado L/L", price: "€1.50" },
      { name: "Cortado condensed milk", price: "€1.50" },
      { name: "Leche y leche (large)", price: "€1.80" },
      { name: "Coffee with milk", price: "€1.70" },
      { name: "Coffee with milk (large)", price: "€2.50" },
      { name: "Americano", price: "€1.30" },
      { name: "Cappuccino", price: "€2.00" },
      { name: "Carajillo", price: "€1.60" },
      { name: "Barraquito (with liqueur)", price: "€2.50" },
      { name: "Ice latte", price: "€3.00" },
      { name: "Ice latte Nutella", price: "€3.90" },
      { name: "Irish coffee", price: "€5.10" },
      { name: "Frappé coffee", price: "€4.10" },
      { name: "Tea or infusions", price: "€1.60" },
      { name: "Matcha tea with orange", price: "€5.00" },
      { name: "Matcha tea (water / milk / plant milk)", price: "€3.00 / €3.50 / €3.50" },
      { name: "Hot chocolate", price: "€2.60" },
      { name: "ColaCao", price: "€2.00" },
    ],
  },
  {
    id: "refrescos",
    title: "Soft drinks",
    dishes: [
      { name: "Sprite / Coca-Cola / Coca-Cola Zero / Fanta", price: "€2.20" },
      { name: "Clipper", price: "€1.80" },
      { name: "Appletizer", price: "€2.20" },
      { name: "Schweppes Lemon", price: "€2.00" },
      { name: "Nestea / Aquarius", price: "€2.20" },
      { name: "Monster", price: "€2.90" },
      { name: "Tonic", price: "€1.90" },
      { name: "Sparkling water", price: "€1.50" },
      { name: "Water (small / large)", price: "€1.20 / €2.20" },
    ],
  },
  {
    id: "cerveza",
    title: "Beer",
    dishes: [
      { name: "Tacoa (Canarian craft)", price: "€3.90" },
      { name: "Draft / jug", price: "€1.50 / €3.00" },
      { name: "Clarita draft / jug", price: "€1.80 / €3.60" },
      { name: "Turia (draft / jug)", price: "€1.80 / €3.60" },
      { name: "Turia (bottle)", price: "€2.20" },
      { name: "Dorada Pilsen", price: "€1.80" },
      { name: "Dorada Especial", price: "€2.00" },
      { name: "Heineken", price: "€1.90" },
      { name: "Corona", price: "€2.50" },
      { name: "1906", price: "€2.30" },
      { name: "Estrella Galicia", price: "€2.30" },
      { name: "Estrella Damm", price: "€1.70" },
      { name: "Voll-Damm", price: "€2.30" },
      { name: "Damm Lemon (shandy)", price: "€1.90" },
      { name: "Free Damm (alcohol-free, gluten-free)", price: "€1.80" },
      { name: "Free Damm Lemon (alcohol-free, gluten-free)", price: "€1.90" },
      { name: "Heineken alcohol-free", price: "€2.10" },
      { name: "Corona alcohol-free", price: "€2.20" },
      { name: "Daura (gluten-free)", price: "€2.20" },
    ],
  },
  {
    id: "vino",
    title: "Wine",
    dishes: [
      { name: "Cava Codorníu Benjamín", price: "€4.50" },
      { name: "Tinto de verano", price: "€3.50" },
      { name: "Red (glass / bottle)", price: "€2.80 / €14.00" },
      { name: "Rosé (glass / bottle)", price: "€3.50 / €18.00" },
      { name: "Dry white (glass / bottle)", price: "€2.80 / €14.00" },
      { name: "Fruity white (glass / bottle)", price: "€3.50 / €18.00" },
      { name: "Sangria (50cl / 1L)", price: "€8.00 / €15.00" },
    ],
  },
  {
    id: "sidra",
    title: "Cider",
    dishes: [
      { name: "Olde English (draft, 25cl / jug)", price: "€2.50 / €5.00" },
      { name: "Kopparberg", price: "€3.50" },
    ],
  },
  {
    id: "cocteles",
    title: "Cocktails",
    dishes: [
      { name: "Piña Colada", price: "€7.00" },
      { name: "Frozen Daiquiri", price: "€7.00" },
      { name: "Mojito (classic / fruit)", price: "€6.50 / €7.00" },
      { name: "Alcohol-free Mojito", price: "€4.50" },
      { name: "Margarita (classic / frozen strawberry)", price: "€6.50" },
      { name: "Mimosa", price: "€3.00" },
      { name: "Aperol Spritz", price: "€7.00" },
      { name: "Campari Spritz", price: "€7.00" },
      { name: "Negroni", price: "€5.50" },
      { name: "Caipirinha", price: "€7.00" },
      { name: "Caipiroska", price: "€7.00" },
      { name: "Long Island", price: "€7.00" },
      { name: "Sex on the Beach", price: "€7.00" },
      { name: "Pornstar Martini", price: "€7.00" },
      { name: "Tequila Sunrise", price: "€7.00" },
      { name: "Espresso Martini", price: "€7.00" },
    ],
  },
  {
    id: "vodka",
    title: "Vodka",
    dishes: [
      { name: "Smirnoff", price: "€3.80" },
      { name: "Absolut", price: "€4.00" },
      { name: "Black", price: "€4.00" },
    ],
  },
  {
    id: "licores",
    title: "Liqueurs",
    dishes: [
      { name: "Baileys", price: "€4.00" },
      { name: "Amaretto", price: "€3.50" },
      { name: "Assorted", price: "€3.50" },
    ],
  },
  {
    id: "vermut",
    title: "Vermouth",
    dishes: [
      { name: "Martini", price: "€3.50" },
      { name: "Campari", price: "€3.50" },
      { name: "Aperol", price: "€3.50" },
    ],
  },
  {
    id: "gin",
    title: "Gin",
    dishes: [
      { name: "Seagram's", price: "€4.60" },
      { name: "Gordon's", price: "€4.60" },
      { name: "Beefeater", price: "€4.60" },
      { name: "Macaronesian", price: "€5.60" },
      { name: "Puerto de Indias", price: "€5.60" },
      { name: "Tanqueray", price: "€5.60" },
      { name: "Bombay Sapphire", price: "€7.50" },
    ],
  },
  {
    id: "ron",
    title: "Rum",
    dishes: [
      { name: "Arehucas Amarillo", price: "€3.50" },
      { name: "Havana 7", price: "€3.80" },
      { name: "Bacardí", price: "€3.80" },
      { name: "Legendario", price: "€3.80" },
    ],
  },
  {
    id: "tequila",
    title: "Tequila",
    dishes: [
      { name: "Tequila (rose / mango / lime)", price: "€3.50" },
    ],
  },
  {
    id: "brandy",
    title: "Brandy",
    dishes: [
      { name: "Veterano", price: "€3.00" },
      { name: "Magno", price: "€3.20" },
      { name: "Rémy Martin", price: "€4.00" },
    ],
  },
  {
    id: "chupitos",
    title: "Shots",
    dishes: [
      { name: "Assorted", price: "€2.00 / €2.50" },
      { name: "Whisky shot", price: "€3.00" },
    ],
  },
  {
    id: "whisky",
    title: "Whisky",
    dishes: [
      { name: "JB", price: "€4.00" },
      { name: "Ballantine's", price: "€4.00" },
      { name: "Johnnie Walker Red", price: "€4.00" },
      { name: "Macallan", price: "€4.50" },
      { name: "Jack Daniel's", price: "€5.00" },
      { name: "Johnnie Walker Black", price: "€5.00" },
      { name: "Glenfiddich 12", price: "€5.00" },
      { name: "Jameson", price: "€5.00" },
    ],
  },
];
