/* ---------------------------------------------------------------------------
   Carta digital de La Dulce — transcrita de su web oficial real
   (ladulcelosabrigos.es), que publica el menú completo en inglés. La versión
   en español es traducción propia de ese mismo contenido verificado.
   --------------------------------------------------------------------------- */

export type Dish = { name: string; price: string };
export type Category = { title: string; dishes: Dish[] };

export const CARTA_EN: Category[] = [
  {
    title: "Brunch",
    dishes: [
      { name: "Eggs Benedict (salmon / bacon / avocado)", price: "€14.95" },
      { name: "Scrambled eggs", price: "€14.95" },
      { name: "Bagels", price: "€14.95" },
      { name: "Pancakes", price: "€14.95" },
      { name: "Toast", price: "€14.95" },
      { name: "Toast Serrano y Manchego", price: "€14.95" },
      { name: "Continental Brunch (2 people)", price: "€29.90" },
    ],
  },
  {
    title: "Breakfast",
    dishes: [
      { name: "Scrambled eggs", price: "€4.00" },
      { name: "Scrambled eggs, bacon or salmon", price: "€8.50" },
      { name: "Scrambled eggs, bacon or Serrano", price: "€7.50" },
      { name: "Eggs Benedict, avocado", price: "€9.50" },
      { name: "Eggs Benedict, bacon", price: "€9.00" },
      { name: "Eggs Benedict, salmon", price: "€9.50" },
      { name: "English breakfast", price: "€8.50" },
    ],
  },
  {
    title: "Pancakes",
    dishes: [
      { name: "Maple syrup", price: "€8.00" },
      { name: "Agave / fruits", price: "€8.00" },
      { name: "Nutella", price: "€8.00" },
      { name: "Dulce de leche", price: "€8.00" },
      { name: "Pistachio paste", price: "€8.00" },
    ],
  },
  {
    title: "Toast",
    dishes: [
      { name: "Jam / butter", price: "€2.50–€3.00" },
      { name: "Oil / tomato", price: "€2.95–€3.50" },
      { name: "Goat cheese", price: "€7.00" },
      { name: "Burrata", price: "€8.90" },
      { name: "Classic", price: "€8.00" },
      { name: "Meli melo", price: "€8.00" },
      { name: "Mushrooms", price: "€8.90" },
      { name: "La Catalana", price: "€8.90" },
      { name: "Cream cheese", price: "€7.60" },
      { name: "Feta cheese", price: "€8.90" },
    ],
  },
  {
    title: "Baguette sandwiches",
    dishes: [
      { name: "Tuna", price: "€5.50" },
      { name: "Pata (leg)", price: "€5.50" },
      { name: "San Blas", price: "€5.90" },
      { name: "Veal", price: "€4.90" },
      { name: "American", price: "€5.50" },
      { name: "Pork loin", price: "€4.90" },
      { name: "French", price: "€4.50" },
      { name: "B-L-T", price: "€4.50" },
      { name: "Shredded chicken", price: "€4.90" },
      { name: "Chicken", price: "€4.90" },
    ],
  },
  {
    title: "Bagels",
    dishes: [
      { name: "Nordic", price: "€8.90" },
      { name: "Tuna", price: "€8.00" },
      { name: "American", price: "€7.90" },
      { name: "Ibérico", price: "€8.90" },
      { name: "Turkey", price: "€6.50" },
    ],
  },
  {
    title: "Small sandwiches (pulga)",
    dishes: [
      { name: "Bacon", price: "€3.20" },
      { name: "White cheese", price: "€3.20" },
      { name: "Salmon", price: "€3.50" },
      { name: "Shredded chicken", price: "€3.20" },
      { name: "Veal", price: "€3.20" },
      { name: "Tenderloin", price: "€3.20" },
      { name: "Tuna", price: "€3.20" },
      { name: "Serrano ham", price: "€3.20" },
      { name: "Turkey", price: "€3.20" },
      { name: "Leg (pata)", price: "€3.20" },
      { name: "Gluten-free version", price: "+€1.00" },
    ],
  },
  {
    title: "Sandwiches",
    dishes: [
      { name: "Mixed", price: "€3.00" },
      { name: "American", price: "€5.00" },
      { name: "Chicken", price: "€5.00" },
      { name: "Tuna", price: "€5.00" },
      { name: "Club sandwich", price: "€8.90" },
    ],
  },
  {
    title: "Croissants",
    dishes: [
      { name: "Plain", price: "€3.30" },
      { name: "Ham and cheese", price: "€3.50" },
      { name: "Chicken", price: "€5.40" },
      { name: "Nutella", price: "€3.50" },
    ],
  },
  {
    title: "Salads",
    dishes: [
      { name: "Caesar", price: "€10.50" },
      { name: "The French", price: "€10.50" },
      { name: "Burrata", price: "€11.50" },
      { name: "Greek", price: "€10.50" },
      { name: "La Dulce", price: "€11.50" },
      { name: "Classic", price: "€10.50" },
    ],
  },
  {
    title: "Bowls & yoghurts",
    dishes: [
      { name: "With fruit", price: "€7.50" },
      { name: "Açaí (frozen)", price: "€9.50" },
    ],
  },
  {
    title: "Burgers",
    dishes: [
      { name: "American", price: "€10.90" },
      { name: "Vegan HËURA", price: "€12.50" },
      { name: "Smash", price: "€11.90" },
      { name: "Mexican", price: "€10.90" },
      { name: "Wilder", price: "€12.95" },
      { name: "La Dulce", price: "€11.90" },
      { name: "Goat cheese", price: "€12.95" },
      { name: "Cheeseburger", price: "€8.00" },
    ],
  },
  {
    title: "Snacking",
    dishes: [
      { name: "Nachos", price: "€10.00" },
      { name: "Broken eggs", price: "€11.00" },
      { name: "Croquettes", price: "€6.50" },
      { name: "Board", price: "€14.00" },
      { name: "Jalapeño peppers", price: "€6.50" },
      { name: "Artichoke", price: "€5.00" },
      { name: "Chicken fingers", price: "€8.00" },
    ],
  },
  {
    title: "Potatoes",
    dishes: [
      { name: "French fries", price: "€3.50" },
      { name: "Crazy fries", price: "€5.50" },
      { name: "Sweet potato fries, parmesan", price: "€6.90" },
      { name: "Sweet potato fries, yoghurt", price: "€6.90" },
    ],
  },
  {
    title: "Mains",
    dishes: [
      { name: "Meat lasagne", price: "€8.50" },
      { name: "La Dulce omelette", price: "€11.90" },
      { name: "Chicken breast", price: "€8.00" },
      { name: "Loin", price: "€8.00" },
    ],
  },
  {
    title: "Cakes",
    dishes: [
      { name: "Apple pie", price: "€4.90" },
      { name: "Cheesecake", price: "€5.00" },
      { name: "Strawberry cake", price: "€5.00" },
      { name: "Lemon pie", price: "€5.00" },
      { name: "Carrot cake", price: "€5.00" },
      { name: "Red velvet", price: "€5.00" },
    ],
  },
  {
    title: "Desserts",
    dishes: [
      { name: "Chocolate brownie", price: "€3.50" },
      { name: "Mousse cups", price: "€3.50" },
      { name: "Chocolate coulant", price: "€3.00" },
      { name: "Fruit tarts", price: "€3.00" },
      { name: "Millefeuille", price: "€2.20" },
      { name: "Polvito uruguayo", price: "€4.00" },
      { name: "Eclair", price: "€2.20" },
    ],
  },
  {
    title: "Natural juices",
    dishes: [
      { name: "Orange (small / large)", price: "€2.30 / €5.90" },
      { name: "Combined (1 / 2 / 3 fruits)", price: "€3.50 / €4.50 / €5.00" },
      { name: "The Red / Green / Fresh / The One", price: "€4.50" },
      { name: "Zumit smoothies", price: "€4.90" },
    ],
  },
  {
    title: "Coffee",
    dishes: [
      { name: "Espresso / double", price: "€1.10 / €2.00" },
      { name: "Cortado", price: "€1.40–€1.70" },
      { name: "Coffee with milk", price: "€2.20" },
      { name: "Americano", price: "€1.30" },
      { name: "Cappuccino", price: "€1.90" },
      { name: "Carajillo", price: "€1.60" },
      { name: "Barraquito", price: "€2.50" },
      { name: "Iced coffee", price: "€4.10" },
      { name: "Irish coffee", price: "€5.10" },
      { name: "Frappé coffee", price: "€4.10" },
      { name: "Tea", price: "€1.60" },
      { name: "Matcha tea", price: "€3.00–€3.50" },
      { name: "Hot chocolate", price: "€2.60" },
      { name: "Cocoa", price: "€2.00" },
    ],
  },
  {
    title: "Soft drinks",
    dishes: [
      { name: "Sprite / Coca-Cola / Fanta", price: "€2.20" },
      { name: "Clipper", price: "€1.80" },
      { name: "Appletizer", price: "€2.00" },
      { name: "Schweppes / Nestea / Aquarius", price: "€2.00–€2.20" },
      { name: "Red Bull", price: "€2.90" },
      { name: "Tonic", price: "€1.90" },
      { name: "Sparkling water", price: "€1.50" },
      { name: "Water", price: "€1.20–€2.20" },
      { name: "Kombucha", price: "€4.00" },
    ],
  },
  {
    title: "Beer",
    dishes: [
      { name: "Canarian craft beers", price: "€3.90" },
      { name: "Caña / jarra", price: "€1.50–€1.80 / €3.00–€3.60" },
      { name: "Dorada / Heineken / Águila", price: "€1.80–€1.90" },
      { name: "Budweiser / 1906 / Estrella", price: "€2.20–€2.30" },
      { name: "Damm varieties", price: "€1.70–€1.90" },
      { name: "Non-alcoholic", price: "€1.80–€1.90" },
      { name: "Daura (gluten-free)", price: "€2.20" },
      { name: "Sangria (50cl / 1L)", price: "€8.00 / €15.00" },
    ],
  },
  {
    title: "Wine",
    dishes: [
      { name: "Cava", price: "€4.50" },
      { name: "Red, glass / bottle", price: "€2.80–€3.50 / €14.00" },
      { name: "Rosé, glass / bottle", price: "€3.50 / €18.00" },
      { name: "White, glass / bottle", price: "€2.80–€3.50 / €14.00–€18.00" },
      { name: "Prosecco", price: "€4.50" },
    ],
  },
  {
    title: "Cocktails",
    dishes: [
      { name: "Piña Colada", price: "€7.00" },
      { name: "Frozen Daiquiri", price: "€7.00" },
      { name: "Mojito", price: "€6.50–€7.00" },
      { name: "Alcohol-free Mojito", price: "€4.50" },
      { name: "Margarita", price: "€7.00" },
      { name: "Mimosa", price: "€3.00" },
      { name: "Aperol Spritz", price: "€7.00" },
      { name: "Campari Spritz", price: "€7.00" },
      { name: "Negroni", price: "€5.50" },
      { name: "Caipirinha", price: "€7.00" },
      { name: "Caipiroska", price: "€6.00" },
      { name: "Long Island", price: "€7.00" },
      { name: "Sex on the Beach", price: "€7.00" },
      { name: "Pornstar Martini", price: "€7.00" },
      { name: "Tequila Sunrise", price: "€7.00" },
      { name: "Espresso Martini", price: "€7.00" },
      { name: "Blackboard specials", price: "from €5.00" },
    ],
  },
  {
    title: "Spirits",
    dishes: [
      { name: "Tequila", price: "€3.50" },
      { name: "Brandy", price: "€3.00–€4.00" },
      { name: "Liqueurs", price: "€3.50–€4.00" },
      { name: "Shots", price: "€2.00–€3.00" },
      { name: "Vermouth", price: "€3.50" },
      { name: "Whisky", price: "€4.00–€5.00" },
      { name: "Gin Tonic", price: "€4.60–€5.60" },
      { name: "Vodka", price: "€3.80–€4.00" },
      { name: "Rum", price: "€3.50–€3.80" },
    ],
  },
];

export const CARTA_ES: Category[] = [
  {
    title: "Brunch",
    dishes: [
      { name: "Huevos Benedict (salmón / bacon / aguacate)", price: "14,95 €" },
      { name: "Huevos revueltos", price: "14,95 €" },
      { name: "Bagels", price: "14,95 €" },
      { name: "Tortitas", price: "14,95 €" },
      { name: "Tostada", price: "14,95 €" },
      { name: "Tostada de serrano y manchego", price: "14,95 €" },
      { name: "Brunch continental (2 personas)", price: "29,90 €" },
    ],
  },
  {
    title: "Desayunos",
    dishes: [
      { name: "Huevos revueltos", price: "4,00 €" },
      { name: "Huevos revueltos con bacon o salmón", price: "8,50 €" },
      { name: "Huevos revueltos con bacon o serrano", price: "7,50 €" },
      { name: "Huevos Benedict con aguacate", price: "9,50 €" },
      { name: "Huevos Benedict con bacon", price: "9,00 €" },
      { name: "Huevos Benedict con salmón", price: "9,50 €" },
      { name: "Desayuno inglés", price: "8,50 €" },
    ],
  },
  {
    title: "Tortitas",
    dishes: [
      { name: "Sirope de arce", price: "8,00 €" },
      { name: "Agave / frutas", price: "8,00 €" },
      { name: "Nutella", price: "8,00 €" },
      { name: "Dulce de leche", price: "8,00 €" },
      { name: "Pasta de pistacho", price: "8,00 €" },
    ],
  },
  {
    title: "Tostadas",
    dishes: [
      { name: "Mermelada / mantequilla", price: "2,50 € – 3,00 €" },
      { name: "Aceite / tomate", price: "2,95 € – 3,50 €" },
      { name: "Queso de cabra", price: "7,00 €" },
      { name: "Burrata", price: "8,90 €" },
      { name: "Clásica", price: "8,00 €" },
      { name: "Meli melo", price: "8,00 €" },
      { name: "Champiñones", price: "8,90 €" },
      { name: "La Catalana", price: "8,90 €" },
      { name: "Queso crema", price: "7,60 €" },
      { name: "Queso feta", price: "8,90 €" },
    ],
  },
  {
    title: "Bocadillos de baguette",
    dishes: [
      { name: "Atún", price: "5,50 €" },
      { name: "Pata", price: "5,50 €" },
      { name: "San Blas", price: "5,90 €" },
      { name: "Ternera", price: "4,90 €" },
      { name: "Americano", price: "5,50 €" },
      { name: "Lomo de cerdo", price: "4,90 €" },
      { name: "Francés", price: "4,50 €" },
      { name: "B-L-T", price: "4,50 €" },
      { name: "Pollo desmenuzado", price: "4,90 €" },
      { name: "Pollo", price: "4,90 €" },
    ],
  },
  {
    title: "Bagels",
    dishes: [
      { name: "Nórdico", price: "8,90 €" },
      { name: "Atún", price: "8,00 €" },
      { name: "Americano", price: "7,90 €" },
      { name: "Ibérico", price: "8,90 €" },
      { name: "Pavo", price: "6,50 €" },
    ],
  },
  {
    title: "Mini bocadillos (pulga)",
    dishes: [
      { name: "Bacon", price: "3,20 €" },
      { name: "Queso blanco", price: "3,20 €" },
      { name: "Salmón", price: "3,50 €" },
      { name: "Pollo desmenuzado", price: "3,20 €" },
      { name: "Ternera", price: "3,20 €" },
      { name: "Solomillo", price: "3,20 €" },
      { name: "Atún", price: "3,20 €" },
      { name: "Jamón serrano", price: "3,20 €" },
      { name: "Pavo", price: "3,20 €" },
      { name: "Pata", price: "3,20 €" },
      { name: "Versión sin gluten", price: "+1,00 €" },
    ],
  },
  {
    title: "Bocadillos",
    dishes: [
      { name: "Mixto", price: "3,00 €" },
      { name: "Americano", price: "5,00 €" },
      { name: "Pollo", price: "5,00 €" },
      { name: "Atún", price: "5,00 €" },
      { name: "Club sandwich", price: "8,90 €" },
    ],
  },
  {
    title: "Croissants",
    dishes: [
      { name: "Natural", price: "3,30 €" },
      { name: "Jamón y queso", price: "3,50 €" },
      { name: "Pollo", price: "5,40 €" },
      { name: "Nutella", price: "3,50 €" },
    ],
  },
  {
    title: "Ensaladas",
    dishes: [
      { name: "César", price: "10,50 €" },
      { name: "La Francesa", price: "10,50 €" },
      { name: "Burrata", price: "11,50 €" },
      { name: "Griega", price: "10,50 €" },
      { name: "La Dulce", price: "11,50 €" },
      { name: "Clásica", price: "10,50 €" },
    ],
  },
  {
    title: "Bowls y yogures",
    dishes: [
      { name: "Con fruta", price: "7,50 €" },
      { name: "Açaí (helado)", price: "9,50 €" },
    ],
  },
  {
    title: "Hamburguesas",
    dishes: [
      { name: "Americana", price: "10,90 €" },
      { name: "Vegana HËURA", price: "12,50 €" },
      { name: "Smash", price: "11,90 €" },
      { name: "Mexicana", price: "10,90 €" },
      { name: "Wilder", price: "12,95 €" },
      { name: "La Dulce", price: "11,90 €" },
      { name: "Queso de cabra", price: "12,95 €" },
      { name: "Cheeseburger", price: "8,00 €" },
    ],
  },
  {
    title: "Para picar",
    dishes: [
      { name: "Nachos", price: "10,00 €" },
      { name: "Huevos rotos", price: "11,00 €" },
      { name: "Croquetas", price: "6,50 €" },
      { name: "Tabla", price: "14,00 €" },
      { name: "Jalapeños", price: "6,50 €" },
      { name: "Alcachofa", price: "5,00 €" },
      { name: "Tiras de pollo", price: "8,00 €" },
    ],
  },
  {
    title: "Patatas",
    dishes: [
      { name: "Patatas fritas", price: "3,50 €" },
      { name: "Patatas locas", price: "5,50 €" },
      { name: "Boniato frito con parmesano", price: "6,90 €" },
      { name: "Boniato frito con yogur", price: "6,90 €" },
    ],
  },
  {
    title: "Platos principales",
    dishes: [
      { name: "Lasaña de carne", price: "8,50 €" },
      { name: "Tortilla La Dulce", price: "11,90 €" },
      { name: "Pechuga de pollo", price: "8,00 €" },
      { name: "Lomo", price: "8,00 €" },
    ],
  },
  {
    title: "Tartas",
    dishes: [
      { name: "Tarta de manzana", price: "4,90 €" },
      { name: "Tarta de queso", price: "5,00 €" },
      { name: "Tarta de fresa", price: "5,00 €" },
      { name: "Tarta de limón", price: "5,00 €" },
      { name: "Tarta de zanahoria", price: "5,00 €" },
      { name: "Red velvet", price: "5,00 €" },
    ],
  },
  {
    title: "Postres",
    dishes: [
      { name: "Brownie de chocolate", price: "3,50 €" },
      { name: "Vasitos de mousse", price: "3,50 €" },
      { name: "Coulant de chocolate", price: "3,00 €" },
      { name: "Tartaletas de fruta", price: "3,00 €" },
      { name: "Milhojas", price: "2,20 €" },
      { name: "Polvito uruguayo", price: "4,00 €" },
      { name: "Eclair", price: "2,20 €" },
    ],
  },
  {
    title: "Zumos naturales",
    dishes: [
      { name: "Naranja (pequeño / grande)", price: "2,30 € / 5,90 €" },
      { name: "Combinado (1 / 2 / 3 frutas)", price: "3,50 € / 4,50 € / 5,00 €" },
      { name: "The Red / Green / Fresh / The One", price: "4,50 €" },
      { name: "Batidos Zumit", price: "4,90 €" },
    ],
  },
  {
    title: "Café",
    dishes: [
      { name: "Espresso / doble", price: "1,10 € / 2,00 €" },
      { name: "Cortado", price: "1,40 € – 1,70 €" },
      { name: "Café con leche", price: "2,20 €" },
      { name: "Americano", price: "1,30 €" },
      { name: "Capuchino", price: "1,90 €" },
      { name: "Carajillo", price: "1,60 €" },
      { name: "Barraquito", price: "2,50 €" },
      { name: "Café con hielo", price: "4,10 €" },
      { name: "Café irlandés", price: "5,10 €" },
      { name: "Café frappé", price: "4,10 €" },
      { name: "Té", price: "1,60 €" },
      { name: "Té matcha", price: "3,00 € – 3,50 €" },
      { name: "Chocolate caliente", price: "2,60 €" },
      { name: "Cacao", price: "2,00 €" },
    ],
  },
  {
    title: "Refrescos",
    dishes: [
      { name: "Sprite / Coca-Cola / Fanta", price: "2,20 €" },
      { name: "Clipper", price: "1,80 €" },
      { name: "Appletizer", price: "2,00 €" },
      { name: "Schweppes / Nestea / Aquarius", price: "2,00 € – 2,20 €" },
      { name: "Red Bull", price: "2,90 €" },
      { name: "Tónica", price: "1,90 €" },
      { name: "Agua con gas", price: "1,50 €" },
      { name: "Agua", price: "1,20 € – 2,20 €" },
      { name: "Kombucha", price: "4,00 €" },
    ],
  },
  {
    title: "Cerveza",
    dishes: [
      { name: "Cervezas artesanas canarias", price: "3,90 €" },
      { name: "Caña / jarra", price: "1,50 € – 1,80 € / 3,00 € – 3,60 €" },
      { name: "Dorada / Heineken / Águila", price: "1,80 € – 1,90 €" },
      { name: "Budweiser / 1906 / Estrella", price: "2,20 € – 2,30 €" },
      { name: "Variedades Damm", price: "1,70 € – 1,90 €" },
      { name: "Sin alcohol", price: "1,80 € – 1,90 €" },
      { name: "Daura (sin gluten)", price: "2,20 €" },
      { name: "Sangría (50cl / 1L)", price: "8,00 € / 15,00 €" },
    ],
  },
  {
    title: "Vino",
    dishes: [
      { name: "Cava", price: "4,50 €" },
      { name: "Tinto, copa / botella", price: "2,80 € – 3,50 € / 14,00 €" },
      { name: "Rosado, copa / botella", price: "3,50 € / 18,00 €" },
      { name: "Blanco, copa / botella", price: "2,80 € – 3,50 € / 14,00 € – 18,00 €" },
      { name: "Prosecco", price: "4,50 €" },
    ],
  },
  {
    title: "Cócteles",
    dishes: [
      { name: "Piña Colada", price: "7,00 €" },
      { name: "Daiquiri Frozen", price: "7,00 €" },
      { name: "Mojito", price: "6,50 € – 7,00 €" },
      { name: "Mojito sin alcohol", price: "4,50 €" },
      { name: "Margarita", price: "7,00 €" },
      { name: "Mimosa", price: "3,00 €" },
      { name: "Aperol Spritz", price: "7,00 €" },
      { name: "Campari Spritz", price: "7,00 €" },
      { name: "Negroni", price: "5,50 €" },
      { name: "Caipirinha", price: "7,00 €" },
      { name: "Caipiroska", price: "6,00 €" },
      { name: "Long Island", price: "7,00 €" },
      { name: "Sex on the Beach", price: "7,00 €" },
      { name: "Pornstar Martini", price: "7,00 €" },
      { name: "Tequila Sunrise", price: "7,00 €" },
      { name: "Espresso Martini", price: "7,00 €" },
      { name: "Especiales de pizarra", price: "desde 5,00 €" },
    ],
  },
  {
    title: "Licores",
    dishes: [
      { name: "Tequila", price: "3,50 €" },
      { name: "Brandy", price: "3,00 € – 4,00 €" },
      { name: "Licores", price: "3,50 € – 4,00 €" },
      { name: "Chupitos", price: "2,00 € – 3,00 €" },
      { name: "Vermú", price: "3,50 €" },
      { name: "Whisky", price: "4,00 € – 5,00 €" },
      { name: "Gin Tonic", price: "4,60 € – 5,60 €" },
      { name: "Vodka", price: "3,80 € – 4,00 €" },
      { name: "Ron", price: "3,50 € – 3,80 €" },
    ],
  },
];
